" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

""" Bundles {{{
	" Required
	Bundle 'gmarik/vundle'
	" Bundles
	Bundle 'Lokaltog/vim-easymotion'    
	Bundle 'Townk/vim-autoclose'        
	Bundle 'ap/vim-css-color'           
	Bundle 'bling/vim-airline'          
	Bundle 'bling/vim-bufferline'       
	Bundle 'chrisbra/SudoEdit.vim'      
	Bundle 'ervandew/supertab'          
	Bundle 'hail2u/vim-css3-syntax'     
	Bundle 'kien/ctrlp.vim'             
	Bundle 'majutsushi/tagbar'          
	Bundle 'othree/html5.vim'           
	Bundle 'scrooloose/nerdcommenter'   
	Bundle 'scrooloose/nerdtree'        
	Bundle 'scrooloose/syntastic'       
	Bundle 'shawncplus/phpcomplete.vim' 
	Bundle 'tpope/vim-fugitive'         
	Bundle 'tpope/vim-markdown'
	Bundle 'tpope/vim-surround'         
	Bundle 'vim-scripts/Align'          
	Bundle 'xuhdev/SingleCompile'       

	""" Additional Action Required Bundles {{{
		" clang_complete requires precompiled library or clang installed
		" Bundle 'Rip-Rip/clang_complete'

		" YouCompleteMe needs 7.3.5xx+, compile with --enable-pythoninterp
		" Bundle 'Valloric/YouCompleteMe'

		" jedi-vim requires Python be installed with jedi package installed
		" Bundle 'davidhalter/jedi-vim'

		" tagbar requires exuberant ctags
		" Bundle 'majutsushi/tagbar'
	""" }}}
""" }}}

""" GUI or Terminal related material {{{
	if has("gui_running")
		set guifont=Terminus\ 11
		set guioptions-=T
		set guioptions-=m
		set guioptions-=r
		let g:solarized_termcolors=256
	endif
	if !has("gui_running")
		" terminal related material here
	endif
""" }}}

""" Interface {{{
	syntax on
	filetype plugin indent on
	set background=dark
	set t_Co=256
	colorscheme hybrid
	au BufRead,BufNewFile *.txt set ft=sh
	hi TabLineFill ctermfg=NONE ctermbg=233
	hi TabLine ctermfg=241 ctermbg=233
	hi TabLineSel ctermfg=250 ctermbg=233
	set cursorline
	set more
	set number
	set title
	set showcmd
	set wildmenu
	set wildmode=longest,list
	set wildignore=.bak,.pyc,.o,.a,.avi,.mkv,.jpg,.jpeg,.png,.so,.gif
	set scrolloff=3
""" }}}

""" General {{{
	set hidden
	set encoding=utf-8
	set history=1000
	set laststatus=2
	set iskeyword+=_,$,#,@,%
	set linebreak
	set nostartofline
	set shortmess+=I
	set splitbelow
	set splitright
	set ttyfast
	set lazyredraw
	set nowrap
	set noshowmode
	""" Folding {{{
		set foldcolumn=0
		set foldmethod=indent
		set foldnestmax=10
		set foldlevelstart=99
	""" }}}
""" }}}

""" Files {{{
	set autochdir
	set autoread
	set confirm
	set noautowrite
	set updatecount=50
	set backupdir=~/.vim/backup,/tmp
	set undofile
	set undodir=~/.vim/undo,/tmp
""" }}}

""" Formatting {{{
	set backspace=indent,eol,start
	set ignorecase
	set autoindent
	set smartindent
	set nrformats+=alpha
	set shiftround
	set shiftwidth=4
	set tabstop=4
	set smarttab
	set smartcase
	set cinkeys-=0#
""" }}}

""" Keys {{{
	let mapleader=","
	map :fig :r!figlet
	map :w! :SudoWrite<CR>
	map <F2> :NERDTreeToggle<CR>
	nmap <F10> :SCCompileRun<cr>
	nmap <F9> :SCCompile<cr>
	nmap <silent> <leader>w :set invwrap<CR>:set wrap?<CR>
	nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
	nnoremap gN :bprevious<CR>
	nnoremap gd :bdelete<CR>
	nnoremap gf <C-^>
	nnoremap gn :bNext<CR>
	noremap <leader>ve :edit $HOME/.vimrc<CR>
	noremap <leader>vs :source $HOME/.vimrc<CR>
	vnoremap <Space> zf
""" }}}

""" Airline {{{
	set ttimeoutlen=50
	" fix unicode symbols
	let g:airline_left_sep = '>>'
	let g:airline_left_sep = '>'
	let g:airline_right_sep = '<<'
	let g:airline_right_sep = '<'
""" }}}

""" Alternative 80 column highlight, automatically enabled {{{
	autocmd BufEnter * highlight OverLength ctermbg=DarkRed ctermfg=white guibg=#cf0000
	autocmd BufEnter * match OverLength /\%80v.*/
""" }}}

""" Show tabs {{{
	set listchars=tab:>\ 
	set list
""" }}}

""" Misc {{{
	let NERDTreeShowHidden = 1 " Show hidden files in NERDTree
	set pastetoggle=<F3>       " Toggle paste mode
	set cc=80                  " colorcolumn, 1 over the limit
	" set textwidth=81                     " textwrapping, try with tw=80 fo=cqt wm=0
	" highlight SpecialKey ctermfg=DarkRed " highlight tab characters
""" }}}
